# Generated by Django 5.1.1 on 2025-04-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='location_coordinates',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='qrlocation',
            old_name='qr_code_data',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_rooms',
            new_name='favorites',
        ),
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='active_until',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='target_building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location_coordinates',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='source',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='query',
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_end', to='navigation.room'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_start', to='navigation.room'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.room'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.room'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qrlocation',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navigation.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.category'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('visitor', 'Visitor')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitedlocation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.room'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
