# Generated by Django 5.1.1 on 2025-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_building_latitude_building_longitude_room_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=1.0),
        ),
    ]
